### ISSUE TITLE
Nuget package:Invalid Windows Phone target

### ISSUE THREAD

**Issue by spaccabit** [RadicalFx/radical-universal#14]
Install-Package Radical.Windows.Presentation.Universal -pre
Installing 'Radical.Windows.Presentation.Universal 0.0.0.1-Alfa'.
Successfully installed 'Radical.Windows.Presentation.Universal 0.0.0.1-Alfa'.
Adding 'Radical.Windows.Presentation.Universal 0.0.0.1-Alfa' to App3.WindowsPhone.
Uninstalling 'Radical.Windows.Presentation.Universal 0.0.0.1-Alfa'.
Successfully uninstalled 'Radical.Windows.Presentation.Universal 0.0.0.1-Alfa'.
Install failed. Rolling back...
Install-Package : Could not install package 'Radical.Windows.Presentation.Universal 0.0.0.1-Alfa'. You are trying to install this 
package into a project that targets 'WindowsPhoneApp,Version=v8.1', but the package does not contain any assembly references or 
content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1

**Comment by mauroservienti** [comment]
@spaccabit can you add some more info on what you are trying to do? Scenario, type of project and such and such? thanks.

**Comment by spaccabit** [comment]
When i create a Universal app on VS 2013 and add referete at Radical.Windows.Presentation.Universal. Package manager throw the exception.
I had pull request to fix the issue.
I have made a pull request to fix this issue.
The version of NuGet Package Manager  is  2.8.50926.663

**Comment by mauroservienti** [comment]
published, thanks. Could you please test with NuGets 0.0.0.2-Alpha?

**Comment by spaccabit** [comment]
Yes, it work

**Comment by mauroservienti** [comment]
closing, thanks.
