### ISSUE TITLE
Change the root namespace from Topics.Radical to Radical

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/radical-universal#9]
Should be done ASAP, before we release the first package on NuGet

--

Related to: https://github.com/RadicalFx/housekeeping/issues/8

**Comment by enosrecanati** [comment]
Commited in [3176b56a03942de30b3f518b38e100c79bb9a55d](https://github.com/RadicalFx/radical-universal/commit/3176b56a03942de30b3f518b38e100c79bb9a55d)

**Comment by mauroservienti** [comment]
great! thanks
